project:
  type: website
  output-dir: docs

website:
  title: ""
  site-url: https://carbon-i.github.io/
  twitter-card: true
  open-graph: true
  google-analytics: "G-PE6RLP594L"
  favicon: img/ci_icon.png
  navbar:
    logo: "/img/Logo-Black2.png"
    background: transparent
    left:
      - href: index.qmd
        text: Home
      - href: team.qmd
        text: Team
      - href: science.qmd
        text: Science
      - href: publications.qmd
        text: Publications
      - text: Visual Stories
        menu:
          - text: CH4 
            href:  ch4_story.qmd
          - href: clouds.qmd
            text: Clouds
      - href: news.qmd
        text: News
    right:
      - icon: github
        href: https://github.com/Carbon-I/
        aria-label: GitHub
  page-footer:
    left: |
      [![](/img/Caltech_Logo.png){fig-alt="Caltech" height=20px}](https://www.caltech.edu/) &nbsp;&nbsp;&nbsp;&nbsp;
      [![](/img/Carnegie.svg){fig-alt="Carnegie" height=20px}](https://carnegiescience.edu/) &nbsp;&nbsp;&nbsp;&nbsp;
      [![](/img/img_acmg_logo_seas.png){fig-alt="Harvard" height=20px}](https://eps.harvard.edu/)
    #center:
    #  - text: "About"
    #    href: about.qmd
    #  - text: "FAQ"
    #    href: docs/faq/index.qmd 
    #  - text: "License"
    #    href: license.qmd
    #  - text: "Trademark"
    #    href: trademark.qmd

    right:
      - text: "{{< ai google-scholar >}} Google Scholar"
        href: https://scholar.google.com/citations?user=7XYDtdYAAAAJ&hl=en 
      - icon: twitter
        href: https://twitter.com/chr_fronge
        aria-label: PI Twitter
      - icon: github
        href: https://github.com/RemoteSensingTools/
        aria-label: Quarto GitHub

format:
  html:
    theme:
      - cosmo
      - styles/custom.scss
    toc: true
    css: styles/custom.css
    page-layout: full
    smooth-scroll: true
    grid:
      sidebar-width: 0px
      body-width: 80%
      margin-width: 150px

editor: visual