project:
  type: website
  output-dir: docs

website:
  title: ""
  site-url: https://carbon-i.github.io/
  twitter-card: true
  open-graph: true
  google-analytics: "G-PE6RLP594L"
  favicon: img/ci_icon.png
  navbar:
    logo: "/img/Logo-White2.png"
    right:
      - href: index.qmd
        text: Home
      - href: team.qmd
        text: Team
      - href: science.qmd
        text: Science
      - href: publications.qmd
        text: Publications
      - text: Visual Stories
        menu:
          - href: ch4_story.qmd
            text: CH4 
          - href: clouds.qmd
            text: Clouds
          - href: spectra.qmd
            text: Surface Spectra
      - href: news.qmd
        text: News
      - icon: github
        href: https://github.com/Carbon-I/
        aria-label: GitHub
  page-footer:
    border: false
    left: |
      ![](/img/Caltech_Logo.png) <br>
      Lead Institution
    center: |
      ![](/img/jpl_logo.png) <br>
      <p>Instrument and 
      Mission Management</p> 
    right: |
      ![](/img/lockheed_logo.png)<br>
      Spacecraft and 
      Mission Operations

    #center:
    #  - text: "About"
    #    href: about.qmd
    #  - text: "FAQ"
    #    href: docs/faq/index.qmd 
    #  - text: "License"
    #    href: license.qmd
    #  - text: "Trademark"
    #    href: trademark.qmd

    # right:
    #   - text: "{{< ai google-scholar >}} Google Scholar"
    #     href: https://scholar.google.com/citations?user=7XYDtdYAAAAJ&hl=en 
    #   - icon: twitter
    #     href: https://twitter.com/chr_fronge
    #     aria-label: PI Twitter
    #   - icon: github
    #     href: https://github.com/RemoteSensingTools/
    #     aria-label: Quarto GitHub

format:
  html:
    include-after-body: 
      - includes/page-scripts.html
    mainfont: "Roboto"
    theme:
      - styles/media-queries.scss
      - styles/custom.scss

    toc: true
    css: 
      - styles/custom.css


    page-layout: custom
    smooth-scroll: true
    grid:
      sidebar-width: 0px
      body-width: 1500px
      margin-width: 150px
