project:
  type: website
  output-dir: docs

website:
  title: ""
  site-url: https://carbon-i.github.io/
  twitter-card: true
  open-graph: true
  google-analytics: "G-PE6RLP594L"
  favicon: img/ci_icon.png
  navbar:
    logo: "/img/Logo-White.png"
    right:
      - href: index.qmd
        text: Home
      - href: team.qmd
        text: Team
      - href: science.qmd
        text: Science
      - href: publications.qmd
        text: Publications
      - text: Visual Stories
        menu:
          - text: CH4 
            href:  ch4_story.qmd
          - href: clouds.qmd
            text: Clouds
      - href: news.qmd
        text: News
      - icon: github
        href: https://github.com/Carbon-I/
        aria-label: GitHub
  page-footer:
    border: false
    left: |
      ![](/img/caltech_logo_white.png) <br>
      Lead Institution
    center: |
      ![](/img/jpl_logo.png) <br>
      <p>Instrument and <br>
      Mission Management</p> 
      <div style="border: 0; border-top: 1px solid white; width: 100%; margin: 1rem auto;"></div>
      <short style="font-size: .80rem"> © 2025 California Institute of Technology. All Rights Reserved.</short>
    right: |
      ![](/img/lockheed_logo.png)<br>
      Spacecraft and <br>
      Mission Operations

    #center:
    #  - text: "About"
    #    href: about.qmd
    #  - text: "FAQ"
    #    href: docs/faq/index.qmd 
    #  - text: "License"
    #    href: license.qmd
    #  - text: "Trademark"
    #    href: trademark.qmd

    # right:
    #   - text: "{{< ai google-scholar >}} Google Scholar"
    #     href: https://scholar.google.com/citations?user=7XYDtdYAAAAJ&hl=en 
    #   - icon: twitter
    #     href: https://twitter.com/chr_fronge
    #     aria-label: PI Twitter
    #   - icon: github
    #     href: https://github.com/RemoteSensingTools/
    #     aria-label: Quarto GitHub

format:
  html:
    include-after-body: includes/custom-footer-banner.html
    mainfont: "Helvetica"
    theme:
      - default
      - styles/custom.scss
    toc: true
    css: styles/custom.css
    page-layout: custom
    smooth-scroll: true
    grid:
      sidebar-width: 0px
      body-width: 1500px
      margin-width: 150px
