---
comments: false
page-layout: custom
toc: false
sidebar: false
format:
  html:
    css: styles/other-background.css  
    margin-top: 0em
    margin-bottom: 0em
    minimal: true
    smooth-scroll: true
    fig-responsive: true
bibliography: publications/cfranken2024_doi.bib
csl: styles/agu.csl
---

:::: {.hero-small .hero-gradient .hero-publications}
::: {.container}
# **PUBLICATIONS**
:::
::::


:::: {.container}
::: {.about .px-md-7 .py-5} 
# Science History and CARBON-I Related Publications

Over the past two decades, remarkable advances have transformed our ability to measure greenhouse gases (GHGs) from space. Carbon-I builds on this legacy—particularly in the emerging field of point-source detection and fine-scale flux quantification. The history of point source detections  began with pioneering work by Dar Roberts and colleagues [@roberts2010mapping] using AVIRIS to identify methane plumes from geological seeps, establishing that imaging spectroscopy could detect trace gas enhancements in complex backgrounds. 

Building on this concept, the first controlled methane release experiment for satellite-style retrieval validation was conducted at the RMOTC facility in Wyoming [@thorpe2016mapping], sponsored by industry and carried out by a team involving several current Carbon-I members. These campaigns demonstrated that kilometer- to meter-scale imaging could resolve individual emission events, sparking a series of retrieval algorithm developments, flight campaigns, and satellite data applications. The first large scale field campaign targeted the Four Corners area in the United States, where a larger methane plume was previously detected from SCIAMACHY [@kort2014four]. Using both AVIRIS-NG as well as HyTES (thermal IR), the team could, for the first time, show the heavy-tailed behavior of methane emissions across larger scales by observing hundreds of methane plumes [@frankenberg2016airborne]. Many more flight campaigns followed [@duren2019california, @cusworth2021quantifying, @cusworth_pnas], led by JPL and eventually leading to the formation of CarbonMapper.

From SCIAMACHY’s early days [@frankenberg2005assessing] to the precision retrievals of GOSAT and OCO-2, each mission taught critical lessons, as nicely summarized in [@jacob2016satellite] and [@jacob2022quantifying]. These include:  

1. sub-nanometer spectral resolution is not always essential for plume or regional flux retrievals [@thorpe2014retrieval; @jongaramrungruang2021remote; @cusworth2019potential];  
2. retrieval reliability in the humid tropics is significantly limited at coarse resolutions [@frankenberg2024data];  
3. only high spatial resolution enables attribution, ground-truthing, and improved cloud avoidance in challenging regions [@frankenberg2024data].

Carbon-I unites these lessons with modern algorithmic and instrumental advances. Our team has published extensively on GHG remote sensing, plume detection, and inversion modeling. The following bibliography highlights key publications from Carbon-I team members that underpin our current science and technical approach. This list is evolving and will be expanded as additional studies are released.


 Our retrieval and point flux inversion approach is based on many publication from Carbon-I team members, e.g. @jongaramrungruang2019towards, @jongaramrungruang2021remote, @jongaramrungruang2022methanet, @thompson2016aliso, @thompson2016space, @frankenberg2016airborne, @ayasse2018evaluating, @borchardt2020detection, @cusworth2019potential, @cusworth2021multisatellite, @cusworth2021quantifying, @duren2019california, @foote2020fast, @thorpe2014retrieval, @thorpe2016airborne, @thorpe2016mapping, @thorpe2017airborne, @thorpe2020methane, @thorpe2023attribution, @thorpe2023methane, @frankenberg2005assessing, @frankenberg2005iterative, @frankenberg2006satellite, @frankenberg2008pressure, @frankenberg2008tropical, @frankenberg2011global 

:::
::::