---
title: "LA Times article"
description: "AAAS media fellow Noah Haggerty reports on our journey "
author: "Christian Frankenberg"
date: "07/02/2024"
image: "https://ca-times.brightspotcdn.com/dims4/default/c1d48a3/2147483647/strip/true/crop/4951x3300+0+1/resize/2000x1333!/format/webp/quality/75/?url=https%3A%2F%2Fcalifornia-times-brightspot.s3.amazonaws.com%2F2f%2Fbd%2Ff281ce604373a2bc3f0498a76d96%2Favirris-jpl-004.jpg"
categories:
  - Greenhouse Gases
  - Earth System Explorer
  - Satellite mission
  - Remote Sensing
---


## LA Times article on Carbon-I efforts

AAAS media fellow [Noah Haggerty](https://www.aaas.org/programs/mass-media-fellowship/noah-haggerty) just published a nice article on our efforts to tackle greenhouse gases from airborne and satellite platforms, paving the way for the Carbon-I mission concept. The article can be found [here](https://www.latimes.com/environment/story/2024-07-02/nasa-jpl-hopes-to-boost-this-satellites-vision). It nicely outlines our path from the [Four Corners campaign](https://www.pnas.org/doi/full/10.1073/pnas.1605617113) to more routine observations of methane plumes. We have come a long way and have to go further still. Maybe we should follow up with a post here about the history of methane observations from space...  

To quote the article and re-quote our Co-PI [Anna Michalak](https://michalak.sites.stanford.edu/):

The NASA program for which Carbon-I was selected as a finalist aims to fund space-based Earth science that will benefit society. The team was awarded $5 million to sharpen its project proposal before a final NASA review in 2025. There are three other finalists, and two will be selected for the launch.

This two-step process for selecting missions is new for NASA’s Earth science programs and requires JPL to compete with the rest of the scientific community, independent of their association with the space agency.

“If we’re talking about grocery money, $5 million seems like a lot of money, but it’s really a bargain,” said Michalak. “If you think about the fact that you’re committing $300 million toward a mission, spending 1.5% of that to really make sure it’s going to be fabulous and successful is extremely smart.”

In the meantime, the Carbon-I team is focused on showing NASA that it has the technical know-how to execute the project on time and under budget.

“I think all four of the missions in the current phase are absolutely worthwhile scientific missions,” said Michalak, “and 50% odds are not bad odds for a satellite mission.”