on:
  workflow_dispatch:
  push:
    branches: main

name: Quarto Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # Change to your preferred Python version
      
      - name: Install dependencies
        run: |
          pip install jupyter

      - name: Julia
        uses: julia-actions/setup-julia@v1

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Install Extensions
        run: |
          quarto install extension mcanouil/quarto-iconify --no-prompt
          quarto install extension quarto-ext/fontawesome --no-prompt
          quarto install extension schochastics/academicons --no-prompt
          quarto install extension quarto-ext/lightbox --no-prompt

      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
