on:
  pull_request:

name: Quarto Render

jobs:
  render-only:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Install Extensions
        run: |
          quarto install extension mcanouil/quarto-iconify --no-prompt
          quarto install extension quarto-ext/fontawesome --no-prompt
          quarto install extension schochastics/academicons --no-prompt

      - name: Render Quarto Project
        uses: quarto-dev/quarto-actions/render@v2
